version: '3.8'

services:
    api:
        build: ./buddy_guyAI_api
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - ./buddy_guyAI_api/:/usr/src/app/
            - ./static_volume:/usr/src/app/staticfiles
            - ./media_volume:/usr/src/app/mediafiles
        ports:
            - 8000:8000 
        env_file:
            - ./.env.dev
#     api-db:
#         image: postgres:13-alpine
#         volumes:
#             - postgres_data:/var/lib/postgresql/data/
#         environment:
#             - POSTGRES_USER=postgres
#             - POSTGRES_PASSWORD=postgres
#             - POSTGRES_DB=api_dev
    
# volumes:
#     postgres_data:
