# Generated by Django 3.2.2 on 2021-07-16 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_doctor_patient'),
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadPrivate',
        ),
        migrations.AddField(
            model_name='upload',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.patient'),
        ),
    ]
